[package]
name = "ewsms43"
version = "0.1.0"
edition = "2021"

[dependencies]
glium = "0.35.0"
imgui = "*"
imgui-glium-renderer = "*"
imgui-winit-support = "*"
lazy_static = "1.5.0"
rfd = "*"
thiserror = "2.0.17"
winit = "*"
